# Generated by Django 5.2.16 on 2026-07-24 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FonteConhecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('url', 'Página web (scraping)'), ('texto', 'Texto colado'), ('arquivo', 'Arquivo enviado')], default='url', max_length=16)),
                ('url', models.URLField(blank=True, default='', max_length=1000)),
                ('descricao', models.TextField(blank=True, default='')),
                ('seguir_links', models.BooleanField(default=False, verbose_name='Seguir links internos')),
                ('profundidade_max', models.PositiveSmallIntegerField(default=1, verbose_name='Profundidade máxima')),
                ('ativo', models.BooleanField(default=True)),
                ('ultima_ingestao_em', models.DateTimeField(blank=True, null=True)),
                ('ultima_ingestao_ok', models.BooleanField(blank=True, null=True)),
                ('ultima_ingestao_detalhe', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'fonte de conhecimento',
                'verbose_name_plural': 'fontes de conhecimento',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='RegraParametrizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo', models.CharField(help_text="Chave 'GRUPO.campo' (ex.: ICMS.CST) ou só 'campo' como fallback.", max_length=120, unique=True)),
                ('categoria', models.CharField(blank=True, default='', max_length=60)),
                ('area', models.CharField(blank=True, default='', help_text="Ex.: 'Regras de tributação', 'Cadastro de produto'. Preencha conforme a versão do cliente.", max_length=200, verbose_name='Área / rotina no Senior')),
                ('orientacao', models.TextField(verbose_name='Orientação ao consultor')),
                ('referencia_url', models.URLField(blank=True, default='', max_length=1000)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'regra de parametrização',
                'verbose_name_plural': 'regras de parametrização',
                'ordering': ['campo'],
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=400)),
                ('url', models.URLField(blank=True, default='', max_length=1000)),
                ('conteudo', models.TextField()),
                ('hash_conteudo', models.CharField(db_index=True, max_length=64)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('fonte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='conhecimento.fonteconhecimento')),
            ],
            options={
                'verbose_name': 'documento',
                'verbose_name_plural': 'documentos',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='Trecho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('titulo_secao', models.CharField(blank=True, default='', max_length=400)),
                ('texto', models.TextField()),
                ('embedding', models.JSONField(blank=True, default=list)),
                ('modelo_embedding', models.CharField(blank=True, default='', max_length=120)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trechos', to='conhecimento.documento')),
            ],
            options={
                'verbose_name': 'trecho',
                'verbose_name_plural': 'trechos',
                'ordering': ['documento_id', 'ordem'],
            },
        ),
        migrations.AddConstraint(
            model_name='documento',
            constraint=models.UniqueConstraint(fields=('fonte', 'hash_conteudo'), name='doc_unico_por_fonte'),
        ),
        migrations.AddIndex(
            model_name='trecho',
            index=models.Index(fields=['documento', 'ordem'], name='conheciment_documen_50a9af_idx'),
        ),
    ]
