# Generated by Django 5.2.16 on 2026-07-24 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conhecimento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fonteconhecimento',
            name='urls',
            field=models.JSONField(blank=True, default=list, verbose_name='URLs'),
        ),
        migrations.AlterField(
            model_name='fonteconhecimento',
            name='tipo',
            field=models.CharField(choices=[('url', 'Página web (scraping)'), ('lista', 'Lista de páginas web'), ('texto', 'Texto colado'), ('arquivo', 'Arquivo enviado')], default='url', max_length=16),
        ),
    ]
