# Generated by Django 5.2.16 on 2026-07-31 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conhecimento', '0002_fonteconhecimento_urls_alter_fonteconhecimento_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TarefaIndexacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('rodando', 'Em andamento'), ('concluida', 'Concluída'), ('erro', 'Falhou')], default='rodando', max_length=12)),
                ('total_inicial', models.PositiveIntegerField(default=0)),
                ('processados', models.PositiveIntegerField(default=0)),
                ('trechos', models.PositiveIntegerField(default=0)),
                ('com_embedding', models.PositiveIntegerField(default=0)),
                ('pendentes', models.PositiveIntegerField(default=0)),
                ('mensagem', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'tarefa de indexação',
                'verbose_name_plural': 'tarefas de indexação',
                'ordering': ['-criado_em'],
            },
        ),
    ]
