# Generated by Django 5.2.16 on 2026-07-24 19:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comparacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('arquivo_cliente', models.CharField(blank=True, default='', max_length=255, verbose_name='Arquivo do cliente')),
                ('arquivo_senior', models.CharField(blank=True, default='', max_length=255, verbose_name='Arquivo da Senior')),
                ('chave_cliente', models.CharField(blank=True, default='', max_length=60)),
                ('chave_senior', models.CharField(blank=True, default='', max_length=60)),
                ('status', models.CharField(choices=[('ok', 'Concluída'), ('erro', 'Erro')], default='ok', max_length=10)),
                ('mensagem_erro', models.TextField(blank=True, default='')),
                ('resumo', models.JSONField(blank=True, default=dict)),
                ('resultado', models.JSONField(blank=True, default=dict)),
                ('relatorio_markdown', models.TextField(blank=True, default='')),
                ('total_divergencias', models.PositiveIntegerField(default=0)),
                ('total_criticas', models.PositiveIntegerField(default=0)),
                ('total_altas', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'comparação',
                'verbose_name_plural': 'comparações',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='DivergenciaRegistrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(db_index=True, max_length=40)),
                ('grupo', models.CharField(blank=True, default='', max_length=40)),
                ('campo', models.CharField(db_index=True, max_length=120)),
                ('caminho', models.CharField(blank=True, default='', max_length=255)),
                ('escopo', models.CharField(default='item', max_length=20)),
                ('tipo', models.CharField(max_length=40)),
                ('severidade', models.CharField(db_index=True, max_length=10)),
                ('valor_cliente', models.TextField(blank=True, default='')),
                ('valor_senior', models.TextField(blank=True, default='')),
                ('diferenca', models.CharField(blank=True, default='', max_length=80)),
                ('item_numero', models.IntegerField(blank=True, null=True)),
                ('item_codigo', models.CharField(blank=True, default='', max_length=80)),
                ('item_descricao', models.CharField(blank=True, default='', max_length=255)),
                ('pista', models.TextField(blank=True, default='')),
                ('comparacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divergencias', to='comparador.comparacao')),
            ],
            options={
                'verbose_name': 'divergência',
                'verbose_name_plural': 'divergências',
                'ordering': ['severidade', 'item_numero', 'campo'],
                'indexes': [models.Index(fields=['comparacao', 'severidade'], name='comparador__compara_d8b6c2_idx')],
            },
        ),
    ]
