# Generated by Django 5.2.16 on 2026-07-24 19:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome_origem_cliente', models.CharField(blank=True, default='', max_length=255)),
                ('nome_origem_senior', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('pareado', 'Pareado — aguardando comparação'), ('comparando', 'Comparando'), ('concluido', 'Concluído'), ('erro', 'Erro')], default='pareado', max_length=12)),
                ('total_cliente', models.PositiveIntegerField(default=0)),
                ('total_senior', models.PositiveIntegerField(default=0)),
                ('total_pares', models.PositiveIntegerField(default=0)),
                ('total_comparados', models.PositiveIntegerField(default=0)),
                ('documentos', models.JSONField(blank=True, default=dict)),
                ('resumo', models.JSONField(blank=True, default=dict)),
                ('relatorio_markdown', models.TextField(blank=True, default='')),
                ('avisos', models.JSONField(blank=True, default=list)),
            ],
            options={
                'verbose_name': 'lote de comparação',
                'verbose_name_plural': 'lotes de comparação',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddField(
            model_name='comparacao',
            name='lote',
            field=models.ForeignKey(blank=True, help_text='Preenchido quando a comparação faz parte de um lote.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comparacoes', to='comparador.lote'),
        ),
        migrations.CreateModel(
            name='ParDocumentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indice', models.PositiveIntegerField(default=0)),
                ('arquivo_cliente', models.CharField(max_length=255)),
                ('arquivo_senior', models.CharField(max_length=255)),
                ('score', models.FloatField(default=0)),
                ('confianca', models.CharField(choices=[('alta', 'Alta'), ('media', 'Média'), ('baixa', 'Baixa'), ('manual', 'Manual')], default='baixa', max_length=8)),
                ('motivos', models.JSONField(blank=True, default=list)),
                ('comparado', models.BooleanField(default=False)),
                ('total_divergencias', models.PositiveIntegerField(default=0)),
                ('total_criticas', models.PositiveIntegerField(default=0)),
                ('total_altas', models.PositiveIntegerField(default=0)),
                ('erro', models.TextField(blank=True, default='')),
                ('comparacao', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='par', to='comparador.comparacao')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pares', to='comparador.lote')),
            ],
            options={
                'verbose_name': 'par de documentos',
                'verbose_name_plural': 'pares de documentos',
                'ordering': ['lote_id', 'indice'],
                'indexes': [models.Index(fields=['lote', 'indice'], name='comparador__lote_id_820f8e_idx')],
            },
        ),
    ]
