# Generated by Django 5.2.16 on 2026-08-12 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=9)),
                ('ncm_prefixo', models.CharField(db_index=True, max_length=8)),
                ('anexo', models.CharField(blank=True, default='', max_length=10)),
                ('segmento', models.CharField(blank=True, default='', max_length=120)),
                ('descricao', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'CEST',
                'verbose_name_plural': 'CEST',
                'ordering': ['codigo', 'ncm_prefixo'],
            },
        ),
        migrations.CreateModel(
            name='Cfop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=4, unique=True)),
                ('descricao', models.CharField(blank=True, default='', max_length=300)),
                ('valido_nfe', models.BooleanField(default=True)),
                ('inicio_vigencia', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'CFOP',
                'verbose_name_plural': 'CFOP',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='FcpUf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(max_length=2, unique=True)),
                ('nome_uf', models.CharField(blank=True, default='', max_length=60)),
                ('tipo', models.CharField(choices=[('fixo', 'Percentual fixo'), ('maximo', 'Percentual máximo')], default='fixo', max_length=8)),
                ('aliquota', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('aliquota_alternativa', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('observacao', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'FCP por UF',
                'verbose_name_plural': 'FCP por UF',
                'ordering': ['uf'],
            },
        ),
        migrations.CreateModel(
            name='VersaoTabela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tabela', models.CharField(max_length=40, unique=True)),
                ('origem', models.URLField(blank=True, default='', max_length=500)),
                ('referencia', models.CharField(blank=True, default='', max_length=300)),
                ('hash_arquivo', models.CharField(blank=True, default='', max_length=64)),
                ('registros', models.PositiveIntegerField(default=0)),
                ('capturado_em', models.DateTimeField()),
                ('importado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'versão de tabela fiscal',
                'verbose_name_plural': 'versões de tabelas fiscais',
                'ordering': ['tabela'],
            },
        ),
        migrations.CreateModel(
            name='Ncm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=8, unique=True)),
                ('descricao', models.TextField()),
                ('descricao_hierarquica', models.TextField(blank=True, default='')),
                ('inicio_vigencia', models.DateField(blank=True, null=True)),
                ('fim_vigencia', models.DateField(blank=True, null=True)),
                ('ato', models.CharField(blank=True, default='', max_length=120)),
            ],
            options={
                'verbose_name': 'NCM',
                'verbose_name_plural': 'NCM',
                'ordering': ['codigo'],
                'indexes': [models.Index(fields=['codigo'], name='ncm_codigo_idx')],
            },
        ),
        migrations.CreateModel(
            name='TipiAliquota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ncm', models.CharField(db_index=True, max_length=8)),
                ('ex', models.PositiveSmallIntegerField(default=0)),
                ('descricao', models.TextField(blank=True, default='')),
                ('aliquota', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('nao_tributado', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'alíquota da TIPI',
                'verbose_name_plural': 'alíquotas da TIPI',
                'ordering': ['ncm', 'ex'],
                'constraints': [models.UniqueConstraint(fields=('ncm', 'ex'), name='tipi_ncm_ex_unico')],
            },
        ),
    ]
