# Generated by Django 5.2.16 on 2026-07-24 19:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comparador', '0001_initial'),
        ('provedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, default='Nova conversa', max_length=200)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('comparacao', models.ForeignKey(blank=True, help_text='Comparação que serve de contexto para esta conversa.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversas', to='comparador.comparacao')),
            ],
            options={
                'verbose_name': 'conversa',
                'verbose_name_plural': 'conversas',
                'ordering': ['-atualizado_em'],
            },
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(choices=[('usuario', 'Consultor'), ('agente', 'Agente'), ('sistema', 'Sistema')], max_length=10)),
                ('conteudo', models.TextField()),
                ('modelo', models.CharField(blank=True, default='', max_length=120)),
                ('fontes', models.JSONField(blank=True, default=list)),
                ('metadados', models.JSONField(blank=True, default=dict)),
                ('erro', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('conversa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='agente.conversa')),
                ('provedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensagens', to='provedores.provedoria')),
            ],
            options={
                'verbose_name': 'mensagem',
                'verbose_name_plural': 'mensagens',
                'ordering': ['criado_em', 'id'],
            },
        ),
    ]
