# Generated by Django 5.2.16 on 2026-07-24 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agente', '0001_initial'),
        ('comparador', '0002_lote_comparacao_lote_pardocumentos'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversa',
            name='lote',
            field=models.ForeignKey(blank=True, help_text='Lote (comparação em massa) que serve de contexto para esta conversa.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversas', to='comparador.lote'),
        ),
        migrations.AlterField(
            model_name='conversa',
            name='comparacao',
            field=models.ForeignKey(blank=True, help_text='Comparação nota a nota que serve de contexto para esta conversa.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversas', to='comparador.comparacao'),
        ),
    ]
