# Generated by Django 5.2.16 on 2026-07-31 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agente', '0002_conversa_lote_alter_conversa_comparacao'),
        ('comparador', '0002_lote_comparacao_lote_pardocumentos'),
        ('provedores', '0002_alter_provedoria_provedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvaliacaoMensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.SmallIntegerField(choices=[(-1, 'Não gostei'), (1, 'Gostei')])),
                ('motivo', models.CharField(blank=True, choices=[('tela_errada', 'Apontou a tela errada'), ('sem_fundamento', 'Resposta sem fundamento na documentação'), ('incompleta', 'Faltou tratar divergências'), ('formato', 'Formato/organização ruim'), ('outro', 'Outro')], default='', max_length=20)),
                ('comentario', models.TextField(blank=True, default='')),
                ('contexto', models.JSONField(blank=True, default=dict)),
                ('chave_sessao', models.CharField(blank=True, default='', max_length=64)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'avaliação de mensagem',
                'verbose_name_plural': 'avaliações de mensagens',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddField(
            model_name='conversa',
            name='chave_sessao',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='mensagem',
            name='prints',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddIndex(
            model_name='conversa',
            index=models.Index(fields=['-atualizado_em'], name='conversa_recentes_idx'),
        ),
        migrations.AddIndex(
            model_name='mensagem',
            index=models.Index(fields=['conversa', 'criado_em'], name='mensagem_conversa_idx'),
        ),
        migrations.AddField(
            model_name='avaliacaomensagem',
            name='mensagem',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacao', to='agente.mensagem'),
        ),
    ]
