# Generated by Django 5.2.16 on 2026-07-24 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProvedorIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text="Como este provedor aparece no seletor do chat. Ex.: 'Claude — produção'.", max_length=80, unique=True, verbose_name='Apelido')),
                ('provedor', models.CharField(choices=[('anthropic', 'Anthropic (Claude)'), ('openai', 'OpenAI'), ('azure_openai', 'Azure OpenAI'), ('google', 'Google (Gemini)'), ('groq', 'Groq'), ('mistral', 'Mistral'), ('deepseek', 'DeepSeek'), ('ollama', 'Ollama (local)'), ('openai_compativel', 'Compatível com OpenAI (base_url)')], max_length=32, verbose_name='Provedor')),
                ('tipo', models.CharField(choices=[('chat', 'Chat / raciocínio'), ('embedding', 'Embeddings (busca semântica)')], default='chat', max_length=16, verbose_name='Tipo')),
                ('modelo', models.CharField(help_text='ID exato do modelo no provedor. Ex.: claude-opus-5, gpt-4o, gemini-2.0-flash.', max_length=120, verbose_name='Modelo')),
                ('api_key_cripto', models.TextField(blank=True, default='', verbose_name='API key (criptografada)')),
                ('base_url', models.URLField(blank=True, default='', help_text='Só para Ollama / Azure / compatíveis.', verbose_name='Base URL')),
                ('versao_api', models.CharField(blank=True, default='', help_text='Usado pelo Azure OpenAI (api-version).', max_length=40, verbose_name='Versão da API')),
                ('temperatura', models.FloatField(default=0.2, verbose_name='Temperatura')),
                ('max_tokens', models.PositiveIntegerField(default=4096, verbose_name='Máx. tokens de saída')),
                ('timeout_segundos', models.PositiveIntegerField(default=120, verbose_name='Timeout (s)')),
                ('parametros_extras', models.JSONField(blank=True, default=dict, help_text='Repassados direto ao construtor do modelo (JSON).', verbose_name='Parâmetros extras')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('padrao', models.BooleanField(default=False, help_text='Usado quando o chat não especifica um provedor.', verbose_name='Padrão')),
                ('ultimo_teste_em', models.DateTimeField(blank=True, null=True, verbose_name='Último teste')),
                ('ultimo_teste_ok', models.BooleanField(blank=True, null=True, verbose_name='Último teste OK')),
                ('ultimo_teste_detalhe', models.TextField(blank=True, default='', verbose_name='Detalhe do teste')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'provedor de IA',
                'verbose_name_plural': 'provedores de IA',
                'ordering': ['tipo', '-padrao', 'nome'],
            },
        ),
    ]
