# Generated by Django 5.2.16 on 2026-07-24 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provedores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provedoria',
            name='provedor',
            field=models.CharField(choices=[('anthropic', 'Anthropic (Claude)'), ('openai', 'OpenAI (GPT)'), ('google', 'Google (Gemini)')], max_length=32, verbose_name='Provedor'),
        ),
    ]
