# Generated by Django 5.2.16 on 2026-08-19 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provedores', '0002_alter_provedoria_provedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provedoria',
            name='provedor',
            field=models.CharField(choices=[('anthropic', 'Anthropic (Claude)'), ('openai', 'OpenAI (GPT)'), ('google', 'Google (Gemini)'), ('azure', 'Azure AI Foundry')], max_length=32, verbose_name='Provedor'),
        ),
    ]
